### ISSUE TITLE
Truly lovely sandbox

### ISSUE THREAD

**Issue by Fastidious** [ckunte/ckunte.github.io#1]
I wanted to be the first to state that ckunte.net is a truly lovely sandbox. I come by a few times a week to peruse old entries, or read what’s new. I am not into offshore structures, but as you keep a fairly varied set of topics, and even make those about your work interesting, I truly like visiting. That’s my feedback! 🙂

I would love to see your theme (source without posts, not rendered), as wouldn’t mind modifying it a little, and use it on my own websites. Have you considered releasing it?

Cheers!

**Comment by ckunte** [comment]
> I wanted to be the first to state that ckunte.net is a truly lovely sandbox. I come by a few times a week to peruse old entries, or read what’s new. I am not into offshore structures, but as you keep a fairly varied set of topics, and even make those about your work interesting, I truly like visiting. That’s my feedback! 🙂

Thank you, you are very kind. 🙏

> I would love to see your theme (source without posts, not rendered), as wouldn’t mind modifying it a little, and use it on my own websites. Have you considered releasing it?

I am not sure if I'd call it a "theme", more a style, which is [just one CSS file][c], and a [very basic HTML structure + Jinja template tags][h]. 🙂 Given that I am using a very custom SSG, the idea of a 'packaged' release never crossed my mind. But as you can see all of it is already online.

[c]: https://github.com/ckunte/ckunte.github.io/blob/master/css/plain.css
[h]: https://github.com/ckunte/chisel/tree/ck/plain
